### ISSUE TITLE
Love the app would love to contribute

### ISSUE THREAD

**Issue by TalkingTeddy** [appstome/timetome-app#2]
Well I am really excited to hear there are many features to release. Is there a way that I can contribute to the project technically? 

I believe this app is built using kotlin and swift. This would give me a nice chance to collaborate and learn.

**Comment by appstome** [comment]
Hi!

Yes, in this project I use modern technologies including Kotlin Multiplatform Project, Jetpack Compose and SwiftUI.

I haven't thought about a collaborative strategy yet. For now, I prefer to go it alone.

The main idea behind publishing the source code is that everyone can fork the code and make features for themselves, because all people have different lifestyles.

**Comment by ferBV** [comment]
I love the app and would love to contribute too, I respect your decision to develop alone but still want to help somehow.

Could you activate the option of "Buy me a coffee"? or some way to donate?
@Medvedev91
