### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [appstome/timetome-app#3]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/5948810622#L5805

**Comment by licaon-kter** [comment]
Sounds like https://gitlab.com/fdroid/fdroiddata/-/issues/3138

Diff log: 
[time461.log](https://github.com/appstome/timetome-app/files/13965092/time461.log)


@appstome how do you build exactly?

**Comment by appstome** [comment]
On the other hand I can create a special buildType and apk for f-droid. I'll try to do that soon.

**Comment by licaon-kter** [comment]
> I was surprised that f-droid automatically build releases from GitHub.

You want only some tags? We can make it skip some, eg. pick up only those that end up in `-fdroid`

 Pipeline says: `.dex` is different, focus on that and on the diff log :)

**Comment by appstome** [comment]
I have no idea what the problem is. [3138](https://gitlab.com/fdroid/fdroiddata/-/issues/) was the [problem](https://gitlab.com/fdroid/fdroiddata/-/issues/3138#note_1687268875), but I [fixed](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13857#note_1697823546) it. There is nothing special in the build process.

Anyway, is it possible for fdroid to use a special flavor "fdroid"? I've already setup [this](https://github.com/appstome/timetome-app/blob/c755a24f7f9ae260b2df6c5c588b05454d6a1d99/android_app/build.gradle.kts#L32). The apk file will be called "fdroid-release.apk".

**Comment by licaon-kter** [comment]
> [3138](https://gitlab.com/fdroid/fdroiddata/-/issues/) was the [problem](https://gitlab.com/fdroid/fdroiddata/-/issues/3138#note_1687268875), but I [fixed](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13857#note_1697823546) it.

Right, so we thought

> I have no idea what the problem is

Same here

> Anyway, is it possible for fdroid to use a special flavor "fdroid"? 

Yes, ping us when you release such a version. What will be different?

**Comment by licaon-kter** [comment]
@appstome how do you build exactly?

OS? IDE? command line? CI?

**Comment by appstome** [comment]
https://github.com/appstome/timetome-app/releases/tag/v2024.01.19.462

> What will be different?

New apk name is "fdroid-release.apk" instead of "android_app-release.apk";

New tags with leading "v" like "v2024.01.19.462" instead of "2024.01.19.462";

Build variant (flavor) "fdroidRelease".

> OS? IDE? command line? CI?

IntelliJ IDEA 2023.2.5 (Ultimate Edition)
Build #IU-232.10227.8, built on November 9, 2023
Runtime version: 17.0.9+7-b1000.46 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    dev.j-a.swift (0.19.0.167-232)
    AceJump (3.8.17)
    IdeaVIM (2.7.5)
    org.jetbrains.IdeaVim-EasyMotion (1.10)
    com.intellij.nativeDebug (232.10203.2)
    com.jetbrains.packagesearch.intellij-plugin (232.9921.28)
    org.jetbrains.kotlin (232-1.9.21-release-633-IJ10072.27)
    org.jetbrains.compose.desktop.ide (1.5.11)
    com.squareup.sqldelight (2.0.1)

Kotlin: 232-1.9.21-release-633-IJ10072.27

**Comment by licaon-kter** [comment]
> Metal Rendering is ON
> Runtime version: 17.0.9+7-b1000.46 aarch64

So macOS on Arm?

**Comment by appstome** [comment]
Arm M1 Pro. The environment is the same as the last successful release. How can I reproduce the error on my local machine to try to solve the problem myself?

**Comment by licaon-kter** [comment]
Interesting, we had another macos built app recently have the same issue: https://github.com/realOxy/M3UAndroid/issues/75#issuecomment-1895446912

Can you do one test? build the APK 2 times and compare sha256 sums

**Comment by appstome** [comment]
(base) ➜  timetome-app git:(main) shasum -a 256 android_app/fdroid/release/fdroid-release.apk
a5cd60a415ba34d97cf03de2e43f5c8df27f4b3f35c85a7ce1a51b062d50cb96  android_app/fdroid/release/fdroid-release.apk
(base) ➜  timetome-app git:(main) shasum -a 256 android_app/fdroid/release/fdroid-release.apk
6ffd03c56f187f883e7f26a8d80f580f0d260e6c25eb0cf4834caab059eaecc6  android_app/fdroid/release/fdroid-release.apk
(base) ➜  timetome-app git:(main) shasum -a 256 android_app/fdroid/release/fdroid-release.apk
6cf46af154863f57c9095ae56acaa1dc30031f1b8205863fe8892c520d89d9e4  android_app/fdroid/release/fdroid-release.apk

Yes, after deleting the "/build" folder and rebuilding this changes.

**Comment by licaon-kter** [comment]
Ok so the tooling is faulty on macOS :(

fyi @linsui

**Comment by licaon-kter** [comment]
@appstome you're building in the IDE (Build->etc) or command line?

**Comment by linsui** [comment]
Oh, the apks built on MacOS are not reproducible themselves?

**Comment by appstome** [comment]
> you're building in the IDE (pressing Build->etc) or command line?

Yes, Build->Generate Signed Bundle / Apk

Tried on IntelliJ IDEA and Android Studio.

**Comment by appstome** [comment]
> Oh, the apks built on MacOS are not reproducible themselves?

I'am not a gradle-expert, I'am a developer :). I think I do something wrong with the build, but I have no clues to dig into it.

**Comment by linsui** [comment]
Can you share the apks?

**Comment by appstome** [comment]
[fdroid-release-79c4193e024018fc445250381082dfb50257cf68a53f5b3a4650eb6aec26aa39.apk.zip](https://github.com/appstome/timetome-app/files/13989930/fdroid-release-79c4193e024018fc445250381082dfb50257cf68a53f5b3a4650eb6aec26aa39.apk.zip)

[fdroid-release-f1969d2039cc4eb00d5bf4571c19a6f654e0b464ddcb57bba36c5000b8ded520.apk.zip](https://github.com/appstome/timetome-app/files/13989935/fdroid-release-f1969d2039cc4eb00d5bf4571c19a6f654e0b464ddcb57bba36c5000b8ded520.apk.zip)

Apks with sha256-names.

**Comment by appstome** [comment]
> 17e3f5c

Ups, the wrong commit message. It should be v2024.01.19.462

> what did you do special?

Nothing. But before building, I deleted the "/build" folder from all modules manually.

**Comment by licaon-kter** [comment]
Maybe that's the trick
