### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by pudup** [appstome/timetome-app#4]
Great app, wish it had a light theme option. Dark / Black themes don't go well with my eyes. 
Thanks

**Comment by appstome** [comment]
The reason I decided to always use a dark theme is the pomodoro timer. Modern displays are significantly less likely to drain the battery while the screen is black.

I know it doesn't make sense while the device is charging, so maybe this will be implemented in the future, but not soon. Sorry :(.

I have ~200 features in the backlog. For now I’am working on the “calendar-like” calendar, instead of the current simple list.

**Comment by pudup** [comment]
That's fine you can take your time. 
My screen is LCD anyway and I prefer LCD so the dark theme doesn't give me any more battery life.

**Comment by appstome** [comment]
Actually, I also prefer using a light theme. The first versions supported both themes, like this https://timeto.me/res/wyou_app/video.mp4, but then I decided to focus on the dark.

So, I've put it on my backlog, but I can't give any deadlines yet.

**Comment by pudup** [comment]
Yeah that looks really nice. I'll just have to wait, you can take your time. I'd make a PR but I'd prolly destroy your app somehow.
